headers: &default_headers
  Accept: application/json
  Content-Type: application/json

default: &default
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  # domain: brokerx.auth0.com
  # audience: https://brokerx.auth0.com/api/v2/
  # connection: BrokerX
  access_token:
    url: /oauth/token
    headers:
      <<: *default_headers
  sign_up:
    url: /api/v2/users
    headers:
      <<: *default_headers

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  domain: auth.brokerxapp.com
